name: bird_scouts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pytorch::pytorch=2.5.1
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip
  - pip:
    - streamlit
    - langchain
    - chromadb
    - fastapi
    - uvicorn
    - google-generativeai
    - librosa
    - opencv-python
    - opentelemetry-api
    - pydantic
    - python-dotenv
    - langchain_google_genai
    - langchain_community
    - langchain_chroma
    - bs4
